import Head from 'next/head'
import Link from 'next/link'
import Layout from '../layouts'


export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs test app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />        
      </Head>
      <Layout>      
        <Link href='/test'>Test</Link>      
      </Layout>
    </>
  )
}
